### PR TITLE
Release 2.0.1

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 2.0.1
| Type?         | 
| BC breaks?    | 
| Deprecations? | 
| Fixed ticket? | 
| How to test?  |

### CODE REVIEW

**Comment by kpodemski** [comment]
@Hlavtox there's a conflict, you can sync your fork dev <-> dev, create a new branch on your fork, pull from master with rebase, and create a PR to fix the conflicts :)

**Review by sallemiines — COMMENTED** [review]
Hello @Hlavtox 
Thanks for the PR ! LGTM QA :heavy_check_mark: 
Module-manager-•-1787 (1)



Stats-•-1787


Thank you ! :rocket:

**Comment by sallemiines** [comment]
> @Hlavtox there's a conflict, you can sync your fork dev <-> dev, create a new branch on your fork, pull from master with rebase, and create a PR to fix the conflicts :)

@Hlavtox could you please check and fix the conflits before merge the PR ! 

Thank you ^^

**Comment by nicosomb** [comment]
@Hlavtox could you fix the conflict please?

**Comment by Hlavtox** [comment]
@nicosomb Krystian was trying, but nothing is working. I think we will need to force push the master branch.

**Review by zuk3975 — APPROVED** [review]

**Review by zuk3975 — APPROVED** [review]

**Review by zuk3975 — DISMISSED** [review]
there are conflicts that needs to be resolved.

**Review by kpodemski — APPROVED** [review]

**Comment by sallemiines** [comment]
Hello , @kpodemski @Hlavtox 

In a fresh shop , when I install the PR I see that there is some conflicts are not resolved yet ! You can see the attached screen shot ! 

image

Could you please check and feedback! 

Thank you !

**Review by nicosomb — APPROVED** [review]

**Comment by florine2623** [comment]
This PR needs a rebase, could you do that please ?

Screenshot 2023-03-01 at 16 45 18

**Review by hibatallahAouadni — COMMENTED** [review]
Hello @Hlavtox 

The new logo is not dosplayed, there's the old logo:

image

It seems that there's problem while you rebase the branch, please check :pray: 
Otherwise all looks good to me.

Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni CTRL+F5

**Review by hibatallahAouadni — APPROVED** [review]
Hello @Hlavtox 

Thanks for helping me to refresh the page :sweat_smile: 
LGTM, QA :heavy_check_mark: 

[statsstock_24.webm](https://user-images.githubusercontent.com/23308427/222751708-c072cfec-adaa-4290-ae4d-35541d4744b5.webm)

**Pull request merged**
